# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
#  h2:
#    console:
#      enabled: true
#      path: "/h2-console"
  datasource:
    url: jdbc:mysql://localhost:3306/ssl_db_jdbc
    username: root
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always # Always execute "schema.sql" when starting boot
  jpa:
    hibernate:
      ddl-auto: none # Let spring boot execute "schema.sql" when starting
  mail:
    host: smtp.gmail.com
    port: 587
    username: yulikexuan@gmail.com
    password: ${EMAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  security:
    runAskey: SSL_RUN_AS_KEY
    permit:
      urls: /h2-console/**, /signup, /user/register, /registrationConfirm*/**, /forgotPassword, /user/resetPassword, /user/changePassword, /js/** # , /favicon*
