# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: logs
      pattern: common
    basedir: target/tomcat
    
security:
  basic:
    enabled: false
  oauth2:
    client: 
      clientId: cloud
      clientSecret: 2PGlgRk9Mv
      # accessTokenUri is the URI to obtain the Access Token
      accessTokenUri: http://localhost:8081/oauth/token
      # userAuthorizationUri is the authorization URI that users will be redirected to
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource: 
      # userInfoUri the URI of user endpoint to obtain current user details
      userInfoUri: http://localhost:8081/user/me
    
spring:
  thymeleaf:
    cache: false

logging:
  level:
    org:
      apache:
        tomcat: INFO
        catalina: INFO