# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8082
  tomcat:
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: logs
      pattern: common
    basedir: target/tomcat
    
spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    jwt:
      signingkey: 6264BB136A72A461C3ACCFB2FC1BF
    client:
      clientId: dms
      clientSecret: 2PGlgRk9Mv
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/user/me

logging:
  level:
    org:
      apache:
        tomcat: INFO
        catalina: INFO