# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8081
  servlet:
    context-path: /ums
spring:
  thymeleaf:
    cache: false
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
  session:
    # Under the hood, Spring Boot applies configuration that is equivalent to
    # manually adding @EnableRedisHttpSession annotation
    # This creates a Spring bean with the name of springSessionRepositoryFilter
    # that implements Filter
    # The filter is in charge of replacing the HttpSession implementation to be
    # backed by Spring Session
    store-type: redis
    # redis.flush-mode
    redis:
      namespace: tecsys:ums:session
  redis:
    host: localhost
    port: 6379
app:
  security:
    permit:
      urls: /h2-console/**,/login**,/dosignin, /oauth/authorize**, /verificationcode
logging:
  level:
    org:
      apache:
        tomcat: INFO
        catalina: INFO
twilio:
  sid: ${TWILIO_SID}
  token: ${TWILIO_TOKEN}
  sender: ${TWILIO_SENDER}
user:
  phone: ${PHONE_NUMBER}