# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: logs
      pattern: common
    basedir: lesson1/target/tomcat
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
app:
  security:
    permit:
      urls: /h2-console/**
logging:
  level:
    org:
      apache:
        tomcat: INFO
        catalina: INFO