# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8080
spring:
  thymeleaf:
    cache: false
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
  security:
    user:
      name: username
      password: password
    basic:
      authorize-mode: authenticated
      path: /**