# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssl_db_jdbc
    username: root
    password: ${MYSQL_PW}
    initialization-mode: always # Always execute data.sql when starting boot
  jpa:
    hibernate:
      ddl-auto: update
    # database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
  h2:
    console:
      enabled: true
      path: "/h2-console"
  mail:
    host: smtp.gmail.com
    port: 587
    username: yulikexuan@gmail.com
    password: ${EMAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  security:
    permit:
      urls: /h2-console/**, /signup, /user/register, /registrationConfirm*/**, /forgotPassword, /user/resetPassword, /user/changePassword, /js/**, /favicon*