# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  jpa:
    show-sql: false
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console:
      enabled: true
      path: "/h2-console"
app:
  security:
    permit:
      urls: /h2-console/**,/login**,/oauth/authorize**
    oauth2:
      jwt:
        signingkey: 6264BB136A72A461C3ACCFB2FC1BF