# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
  h2:
    console:
      enabled: true
      path: "/h2-console"
  mail:
    host: smtp.gmail.com
    port: 587
    username: yulikexuan@gmail.com
    password: ${EMAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  security:
    permit:
      urls: /h2-console/**, /signup, /user/register, /registrationConfirm*/**, /forgotPassword, /user/resetPassword, /user/changePassword, /js/** # , /favicon*