# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8082
  servlet:
    context-path: /dms
    
spring:
  mvc:
    favicon:
      enabled: true
  thymeleaf:
    cache: false

security:
  oauth2:
    sso:
      loginPage: /login
    client:
      clientId: dms
      clientSecret: 2PGlgRk9Mv
      accessTokenUri: http://localhost:8081/ums/oauth/token
      userAuthorizationUri: http://localhost:8081/ums/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8081/ums/api/users/me
      # preferTokenInfo: false
      jwt:
        public-key-location: classpath:sslkey.pub
#        keyUri: http://localhost:8081/ums/oauth/token