# Allow Thymeleaf templates to be reloaded at dev time
server:
  port: 8082
  servlet:
    context-path: /dms
    
spring:
  thymeleaf:
    cache: false

security:
  oauth2:
    sso:
      loginPage: /login
    client:
      clientId: dms
      clientSecret: 2PGlgRk9Mv
      accessTokenUri: http://localhost:8081/oauth/token
      userAuthorizationUri: http://localhost:8081/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: http://localhost:8081/api/users/me
      # preferTokenInfo: false
      jwt:
        keyUri: http://localhost:8081/oauth/token
        keyValue: 6264BB136A72A461C3ACCFB2FC1BF

logging:
  level:
    org:
      apache:
        tomcat: INFO
        catalina: INFO